# Copyright 2021 Syed Mohammad Adnan Karim
# See LICENSE file for licensing details.
options:
  elasticsearch-hostname:
    default: "localhost"
    description: The hostname of your Elasticsearch node
    type: string
  elasticsearch-port:
    default: "9200"
    description: The port number of your Elasticsearch node
    type: string
